#!/usr/bin/env python3
"""
COMPOSER STRATEGY GENERATOR
Automatically generates syntactically correct Composer strategy code
No manual typing = no syntax errors
"""

class ComposerStrategyGenerator:
    """Generate Composer strategy code programmatically"""
    
    def __init__(self):
        self.portfolio = {}
        self.rules = []
        self.rebalance_config = {}
    
    def add_portfolio(self, symbol, allocation):
        """Add portfolio asset"""
        self.portfolio[symbol] = allocation
    
    def add_bull_rule(self):
        """Add BULL regime rule"""
        rule = {
            'name': 'Bull Uptrend',
            'conditions': [
                'SPY > sma(SPY, 20)',
                'sma(SPY, 20) > sma(SPY, 50)',
                'rsi(SPY, 14) > 55'
            ],
            'allocations': {
                'SPY': 0.45,
                'QQQ': 0.45,
                'IWM': 0.20,
                'TLT': 0.03,
                'GLD': 0.02,
                'DBC': 0.00
            }
        }
        self.rules.append(rule)
    
    def add_bear_rule(self):
        """Add BEAR regime rule"""
        rule = {
            'name': 'Bear Downtrend',
            'conditions': [
                'SPY < sma(SPY, 20)',
                'sma(SPY, 20) < sma(SPY, 50)',
                'rsi(SPY, 14) < 45'
            ],
            'allocations': {
                'SPY': 0.15,
                'QQQ': 0.15,
                'IWM': 0.05,
                'TLT': 0.35,
                'GLD': 0.15,
                'DBC': 0.05
            }
        }
        self.rules.append(rule)
    
    def add_chop_rule(self):
        """Add CHOP (neutral) regime rule"""
        rule = {
            'name': 'Neutral Chop',
            'conditions': [
                'SPY > sma(SPY, 20)',
                'SPY < sma(SPY, 50)',
                'rsi(SPY, 14) >= 40',
                'rsi(SPY, 14) <= 60'
            ],
            'allocations': {
                'SPY': 0.35,
                'QQQ': 0.35,
                'IWM': 0.15,
                'TLT': 0.08,
                'GLD': 0.05,
                'DBC': 0.02
            }
        }
        self.rules.append(rule)
    
    def set_rebalancing(self, frequency='daily', time='15:50 ET', tolerance=0.03):
        """Set rebalancing configuration"""
        self.rebalance_config = {
            'frequency': frequency,
            'time': time,
            'tolerance': tolerance
        }
    
    def generate_code(self):
        """Generate complete Composer code"""
        lines = []
        
        # Header
        lines.append("// ═════════════════════════════════════════════════════════════════")
        lines.append("// COMPOSER DAILY ADJUSTMENT STRATEGY - AUTO-GENERATED")
        lines.append("// Generated by ComposerStrategyGenerator")
        lines.append("// ═════════════════════════════════════════════════════════════════")
        lines.append("")
        
        # Portfolio section
        lines.append("// SECTION 1: PORTFOLIO")
        for symbol, allocation in self.portfolio.items():
            lines.append(f"portfolio allocate {symbol} {allocation}")
        lines.append("")
        
        # Rules section
        for i, rule in enumerate(self.rules, 1):
            lines.append(f"// RULE {i}: {rule['name'].upper()}")
            
            # Conditions
            condition_str = " and ".join(rule['conditions'])
            lines.append(f"if {condition_str}:")
            
            # Allocations
            for symbol, allocation in rule['allocations'].items():
                lines.append(f"  allocate {symbol} {allocation}")
            
            lines.append("")
        
        # Rebalancing section
        if self.rebalance_config:
            lines.append("// REBALANCING")
            lines.append(f"rebalance {self.rebalance_config['frequency']} at {self.rebalance_config['time']}")
            lines.append(f"rebalance tolerance {self.rebalance_config['tolerance']}")
        
        return "\n".join(lines)
    
    def save_to_file(self, filename):
        """Save generated code to file"""
        code = self.generate_code()
        with open(filename, 'w') as f:
            f.write(code)
        print(f"✅ Strategy saved to: {filename}")
        return code


def main():
    """Generate the daily adjustment strategy"""
    
    print("═" * 70)
    print("COMPOSER STRATEGY GENERATOR - AUTO-GENERATION")
    print("═" * 70)
    print()
    
    # Initialize generator
    generator = ComposerStrategyGenerator()
    
    # Add portfolio
    print("Adding portfolio...")
    generator.add_portfolio('SPY', 0.35)
    generator.add_portfolio('QQQ', 0.35)
    generator.add_portfolio('IWM', 0.15)
    generator.add_portfolio('TLT', 0.08)
    generator.add_portfolio('GLD', 0.05)
    generator.add_portfolio('DBC', 0.02)
    print("  ✅ Portfolio added (6 assets)")
    
    # Add rules
    print("Adding rules...")
    generator.add_bull_rule()
    print("  ✅ BULL rule added")
    generator.add_bear_rule()
    print("  ✅ BEAR rule added")
    generator.add_chop_rule()
    print("  ✅ CHOP rule added")
    
    # Set rebalancing
    print("Setting rebalancing...")
    generator.set_rebalancing(
        frequency='daily',
        time='15:50 ET',
        tolerance=0.03
    )
    print("  ✅ Rebalancing configured (daily at 15:50 ET)")
    
    # Generate code
    print()
    print("Generating code...")
    code = generator.generate_code()
    
    # Display
    print()
    print("═" * 70)
    print("GENERATED COMPOSER CODE:")
    print("═" * 70)
    print(code)
    print()
    print("═" * 70)
    
    # Save to file
    filename = '/tmp/composer_strategy_auto.txt'
    generator.save_to_file(filename)
    
    print()
    print("✅ STRATEGY COMPLETE!")
    print()
    print("HOW TO USE:")
    print("  1. Copy the code above")
    print("  2. Go to Composer.trade")
    print("  3. Create new strategy")
    print("  4. Paste code into editor")
    print("  5. Click 'Apply Code'")
    print("  6. Backtest")
    print()
    print("═" * 70)


if __name__ == "__main__":
    main()